[project]
name = "yolo-clock"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

dependencies = [
    "numpy",
    "opencv-python",
    "torch",
    "torchvision",
    "ultralytics",
]
[tool.uv.sources]
torch = [
    { index = "pytorch-cu130", marker = "sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu130", marker = "sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true